### ISSUE TITLE
tinyserial: symbol lookup error: tinyserial: undefined symbol: _ZdlPvm, version Qt_5

### ISSUE THREAD

**Issue by Devoe-97** [carloscn/tinyserial#11]
I had installed tinyserial. When I inputed tinyserial command, it outputed 
tinyserial: symbol lookup error: tinyserial: undefined symbol: _ZdlPvm, version Qt_5

**Comment by Devoe-97** [comment]
ubuntu20.04

**Comment by philleer** [comment]
How did you solve it?

**Comment by carloscn** [comment]
fixed on https://github.com/carloscn/tinyserial/releases/tag/v1.4
