### ISSUE TITLE
manjaro 上安装了 打不开 什么都没有 本地能查询到安装了这个包

### ISSUE THREAD

**Issue by artillerymans** [carloscn/tinyserial#3]

**Comment by carloscn** [comment]
看看是不是一些qt的库没有装。

**Comment by carloscn** [comment]
fixed it on https://github.com/carloscn/tinyserial/releases/tag/1.2.0  
Please download the lastest version.
I closed the issue. if have any question, please pull a new issue on the list. thanks very much.
